Sprint 1
stani-novikov/middle.messenger.praktikum.yandex pull request #1
Opened 2022-08-24 15:47 UTC by stani-novikov

2022-08-24 20:42 UTC, podlovchenko requested changes
Привет) В целом все хорошо, но нужно добавить ссылку на нетлифай в ридми и постараться разобраться с лейблом у полей формы

2022-08-24 20:42 UTC, podlovchenko commented on package.json
> +    "express": "^4.18.1",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-08-24 20:42 UTC, podlovchenko commented on package.json
> +    "dev": "parcel src/index.html",
Для запуска на 3000 порту нужно добавить ключ --port

2022-08-24 20:42 UTC, podlovchenko commented on src/pages/authorization/authorization.hbs
> +                    <input class="field__input" name="{{this.name}}" type="{{this.type}}" id="{{ this.id }}">
Так сейчас выглядит поле при вводе текста
<img width="676" alt="Снимок экрана 2022-08-24 в 23 40 08" src="https://user-images.githubusercontent.com/22602747/186519171-fd8b757f-b4f1-4fe5-a4a6-c2d658589cf8.png">
Лучше задать через placeholder значение, либо переместить label в другое место

2022-08-24 20:44 UTC, podlovchenko commented on server.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через [переменное окружение](https://nodejs.org/dist/latest-v8.x/docs/api/process.html):

process.env.PORT || PORT;

2022-08-25 08:07 UTC, stani-novikov commented on package.json
> +    "dev": "parcel src/index.html",
а зачем запускать локальный сервер парселя на 3000 порту? 
Кажется, что требование про 3000 порт в задании относилось к локальному серверу на express

2022-08-25 08:36 UTC, stani-novikov commented on src/pages/authorization/authorization.hbs
> +                    <input class="field__input" name="{{this.name}}" type="{{this.type}}" id="{{ this.id }}">
там была задумка с анимацией, которую я не дописал. 
Сейчас исправлю

2022-08-25 15:27 UTC, podlovchenko commented
Работу принимаю)

2022-08-27 20:03 UTC, merged